// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migration uchun Neon direct URL kerak — pooler pg_advisory_lock ni bloklab qo'yadi.
    // DIRECT_URL o'rnatilmagan bo'lsa, DATABASE_URL'dan "-pooler" olib tashlab yasaymiz.
    url: process.env["DIRECT_URL"] ??
      (process.env["DATABASE_URL"] ?? "").replace(/-pooler(\.\S)/, "$1"),
  },
});
